# Generated by Django 5.1.1 on 2026-01-24 23:32

from django.db import migrations

def seed_user(apps, schema_editor):
    User = apps.get_model('auth', 'User')

    if not User.objects.filter(username='admin').exists():
        User.objects.create_superuser(
            username='demo',
            email='demo@example.com',
            password='demo123'
        )
        
class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(seed_user),
    ]
