# Generated by Django 5.1.1 on 2026-01-26 19:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_seed_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskCustomField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=100)),
                ('field_type', models.CharField(choices=[('string', 'String'), ('boolean', 'Boolean'), ('number', 'Number')], max_length=20)),
                ('field_value', models.JSONField(null=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_fields', to='tasks.task')),
            ],
        ),
    ]
